// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P310_ASP_Start.DAL;

namespace P310_ASP_Start.Migrations
{
    [DbContext(typeof(EliteContext))]
    [Migration("20191014171733_AddedNewArrival")]
    partial class AddedNewArrival
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("P310_ASP_Start.Models.NewArrival", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("NewArrivals");

                    b.HasData(
                        new { Id = 1, Image = "bottom1.jpg", Title = "<span>f</span>all ahead" },
                        new { Id = 2, Image = "bottom2.jpg", Title = "<span>f</span>all ahead" }
                    );
                });

            modelBuilder.Entity("P310_ASP_Start.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new { Id = 1, Image = "banner1.jpg", SubTitle = "Special for today", Title = "The Biggest <span>Sale</span> " },
                        new { Id = 2, Image = "banner2.jpg", SubTitle = "New Arrivals On Sale", Title = "SUMMER <span>COLLECTION </span> " },
                        new { Id = 3, Image = "banner3.jpg", SubTitle = "Special for Kamran", Title = "The Biggest <span>Sale</span> " },
                        new { Id = 4, Image = "banner4.jpg", SubTitle = "Special for Ruslan", Title = "The Biggest <span>Perviz ever</span> " }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
